"""文章模块测试：创建/列表/分页/排序/筛选/详情/权限/点赞/上下篇。"""

from __future__ import annotations

from httpx import AsyncClient

from tests.factories import make_article_payload, make_png_bytes, unique_suffix


class TestCreate:
    async def test_create_draft_has_no_published_at(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        response = await client.post(
            "/api/v1/articles",
            json=make_article_payload(status="draft"),
            headers=author_headers,
        )
        assert response.status_code == 201
        body = response.json()
        assert body["status"] == "draft"
        assert body["published_at"] is None

    async def test_create_published_sets_published_at(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        body = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=author_headers
            )
        ).json()
        assert body["status"] == "published"
        assert body["published_at"] is not None

    async def test_summary_and_reading_time_are_derived(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """不传 summary 时从正文自动抽取；阅读时长按正文长度估算。"""
        body = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(summary=None, content_md="# 标题\n\n" + "内容" * 800),
                headers=author_headers,
            )
        ).json()
        assert body["summary"]
        assert "内容" in body["summary"]
        assert body["reading_time"] >= 1

    async def test_slug_autogenerated_and_unique(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        title = f"重名标题-{unique_suffix()}"
        first = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(title=title), headers=author_headers
            )
        ).json()
        second = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(title=title), headers=author_headers
            )
        ).json()
        assert first["slug"] != second["slug"]
        assert second["slug"].endswith("-2")

    async def test_custom_slug_is_respected(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        body = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(slug="my-custom-slug"),
                headers=author_headers,
            )
        ).json()
        assert body["slug"] == "my-custom-slug"

    async def test_guest_cannot_create(self, client: AsyncClient) -> None:
        response = await client.post("/api/v1/articles", json=make_article_payload())
        assert response.status_code == 401

    async def test_unknown_category_is_rejected(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        response = await client.post(
            "/api/v1/articles",
            json=make_article_payload(category_id=999999),
            headers=author_headers,
        )
        assert response.status_code == 400

    async def test_too_many_tags_rejected(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        response = await client.post(
            "/api/v1/articles",
            json=make_article_payload(tags=[f"标签{i}" for i in range(12)]),
            headers=author_headers,
        )
        assert response.status_code == 422

    async def test_tags_are_created_on_the_fly(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """打一个新标签不该要求先去标签页创建——自由打标签是写作体验的一部分。"""
        name = f"新标签{unique_suffix()}"
        body = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(tags=[name, name]),
                headers=author_headers,
            )
        ).json()
        assert [tag["name"] for tag in body["tags"]] == [name]  # 去重后只剩一个


class TestListAndPagination:
    async def test_pagination_math(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        for _ in range(5):
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=author_headers
            )

        first = (await client.get("/api/v1/articles?page=1&page_size=2")).json()
        assert first["total"] == 5
        assert first["pages"] == 3
        assert len(first["items"]) == 2

        last = (await client.get("/api/v1/articles?page=3&page_size=2")).json()
        assert len(last["items"]) == 1

    async def test_out_of_range_page_keeps_correct_total(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """页码超界时前端要能拿到 total 才知道该弹回第几页，不能直接返回 0。"""
        await client.post("/api/v1/articles", json=make_article_payload(), headers=author_headers)
        body = (await client.get("/api/v1/articles?page=99&page_size=10")).json()
        assert body["total"] == 1
        assert body["items"] == []

    async def test_page_size_upper_bound_enforced(self, client: AsyncClient) -> None:
        response = await client.get("/api/v1/articles?page_size=100000")
        assert response.status_code == 422

    async def test_invalid_page_rejected(self, client: AsyncClient) -> None:
        assert (await client.get("/api/v1/articles?page=0")).status_code == 422

    async def test_list_excludes_content_md(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """列表接口绝不能带正文——这是分页接口最常见的性能事故来源。"""
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(content_md="# 标题\n\n" + "很长很长的正文。" * 500),
            headers=author_headers,
        )
        body = (await client.get("/api/v1/articles")).json()
        assert body["items"]
        assert "content_md" not in body["items"][0]
        assert "comment_count" in body["items"][0]

    async def test_draft_not_in_public_list(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(status="draft"),
            headers=author_headers,
        )
        body = (await client.get("/api/v1/articles")).json()
        assert body["total"] == 0

    async def test_managed_list_shows_own_drafts(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(status="draft"),
            headers=author_headers,
        )
        body = (await client.get("/api/v1/articles/manage/list", headers=author_headers)).json()
        assert body["total"] == 1
        assert body["items"][0]["status"] == "draft"

    async def test_author_managed_list_hides_others_articles(
        self, client: AsyncClient, admin_headers: dict[str, str], author_headers: dict[str, str]
    ) -> None:
        """作者后台只能看自己的——这是默认的保守策略，不需要额外配置。"""
        await client.post("/api/v1/articles", json=make_article_payload(), headers=admin_headers)
        body = (await client.get("/api/v1/articles/manage/list", headers=author_headers)).json()
        assert body["total"] == 0

        admin_view = (
            await client.get("/api/v1/articles/manage/list", headers=admin_headers)
        ).json()
        assert admin_view["total"] == 1


class TestSorting:
    async def _seed_three(self, client: AsyncClient, headers: dict[str, str]) -> None:
        titles = ["第一篇", "第二篇", "第三篇"]
        for index, title in enumerate(titles):
            body = (
                await client.post(
                    "/api/v1/articles",
                    json=make_article_payload(title=title),
                    headers=headers,
                )
            ).json()
            # 用 PATCH 调整阅读量，构造"热度与时间顺序不同"的场景
            if index == 0:
                for _ in range(3):
                    await client.post(f"/api/v1/articles/{body['id']}/like")

    async def test_latest_and_oldest_are_mirror_images(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        await self._seed_three(client, author_headers)
        latest = (await client.get("/api/v1/articles?sort=latest")).json()["items"]
        oldest = (await client.get("/api/v1/articles?sort=oldest")).json()["items"]
        assert [i["id"] for i in latest] == list(reversed([i["id"] for i in oldest]))

    async def test_hottest_sorts_by_view_count(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        ids = []
        for index in range(3):
            body = (
                await client.post(
                    "/api/v1/articles",
                    json=make_article_payload(title=f"热度文章{index}"),
                    headers=author_headers,
                )
            ).json()
            ids.append(body["id"])
        # 给最后一篇（时间上最新）刷最多的阅读量
        for _ in range(3):
            await client.get(f"/api/v1/articles/{ids[-1]}")

        hottest = (await client.get("/api/v1/articles?sort=hottest")).json()["items"]
        assert hottest[0]["id"] == ids[-1]

    async def test_top_article_comes_first_regardless_of_sort(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """置顶的语义就是"永远在最前面"，否则置顶没有意义。"""
        normal = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=author_headers
            )
        ).json()
        pinned = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(is_top=True),
                headers=author_headers,
            )
        ).json()
        oldest_first = (await client.get("/api/v1/articles?sort=oldest")).json()["items"]
        assert oldest_first[0]["id"] == pinned["id"]
        assert oldest_first[1]["id"] == normal["id"]

    async def test_invalid_sort_enum_rejected(self, client: AsyncClient) -> None:
        response = await client.get("/api/v1/articles?sort=drop_table")
        assert response.status_code == 422


class TestFiltering:
    async def test_keyword_search_matches_title_and_body(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        token = unique_suffix()
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(title=f"包含关键词{token}的文章"),
            headers=author_headers,
        )
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(content_md=f"正文里也提到了 {token} 这个词"),
            headers=author_headers,
        )
        await client.post("/api/v1/articles", json=make_article_payload(), headers=author_headers)

        body = (await client.get(f"/api/v1/articles?keyword={token}")).json()
        assert body["total"] == 2

    async def test_like_wildcards_are_escaped(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """不转义的话，搜 `%` 会匹配到所有文章，这是个很隐蔽的 bug。"""
        await client.post("/api/v1/articles", json=make_article_payload(), headers=author_headers)
        body = (await client.get("/api/v1/articles?keyword=%25")).json()
        assert body["total"] == 0

    async def test_filter_by_tag_slug(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        tag = f"筛选标签{unique_suffix()}"
        created = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(tags=[tag]), headers=author_headers
            )
        ).json()
        slug = created["tags"][0]["slug"]
        body = (await client.get(f"/api/v1/articles?tag={slug}")).json()
        assert body["total"] == 1

    async def test_filter_by_category_slug_and_id(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        category = (
            await client.post(
                "/api/v1/categories",
                json={"name": f"分类{unique_suffix()}"},
                headers=author_headers,
            )
        ).json()
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(category_id=category["id"]),
            headers=author_headers,
        )
        by_slug = (await client.get(f"/api/v1/articles?category={category['slug']}")).json()
        by_id = (await client.get(f"/api/v1/articles?category={category['id']}")).json()
        assert by_slug["total"] == by_id["total"] == 1

    async def test_filter_by_author(
        self, client: AsyncClient, admin_headers: dict[str, str], author_id: int
    ) -> None:
        await client.post("/api/v1/articles", json=make_article_payload(), headers=admin_headers)
        body = (await client.get(f"/api/v1/articles?author_id={author_id}")).json()
        assert body["total"] == 0


class TestDetail:
    async def test_detail_by_slug_and_id_are_equivalent(
        self, client: AsyncClient, published_article: dict[str, object]
    ) -> None:
        by_slug = await client.get(f"/api/v1/articles/{published_article['slug']}")
        by_id = await client.get(f"/api/v1/articles/{published_article['id']}")
        assert by_slug.status_code == by_id.status_code == 200
        assert by_slug.json()["id"] == by_id.json()["id"]
        assert by_slug.json()["content_md"] == published_article["content_md"]

    async def test_view_count_increments(
        self, client: AsyncClient, published_article: dict[str, object]
    ) -> None:
        before = published_article["view_count"]
        after = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()[
            "view_count"
        ]
        assert after == before + 1

    async def test_view_does_not_touch_updated_at(
        self, client: AsyncClient, published_article: dict[str, object]
    ) -> None:
        """阅读量变化不是内容修改，不能改 updated_at。

        列上的 ``onupdate`` 对 Core ``update()`` 同样生效，早先没显式钉住它，
        于是**读一次文章就改一次 updated_at**。后果有两个，都是用户可见的：
        后台默认排序 ``sort=updated`` 实际变成「最近被看过的」，热门旧文会压过
        刚编辑过的；sitemap 的 ``<lastmod>`` 每次访问都变，等于告诉爬虫
        全站天天在改。
        """
        first = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()
        assert first["view_count"] == published_article["view_count"] + 1

        # 再读几次，updated_at 必须纹丝不动
        for _ in range(2):
            later = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()
        assert later["view_count"] > first["view_count"]
        assert later["updated_at"] == first["updated_at"]

    async def test_like_does_not_touch_updated_at(
        self, client: AsyncClient, published_article: dict[str, object]
    ) -> None:
        """点赞同理：计数变化不该被当成内容更新。"""
        before = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()
        await client.post(f"/api/v1/articles/{published_article['id']}/like")
        after = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()
        assert after["updated_at"] == before["updated_at"]

    async def test_editing_does_touch_updated_at(
        self,
        client: AsyncClient,
        published_article: dict[str, object],
        author_headers: dict[str, str],
    ) -> None:
        """反向断言：真正的内容修改必须更新 updated_at，别修过头。"""
        before = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()
        await client.patch(
            f"/api/v1/articles/{published_article['id']}",
            json={"summary": "改过的摘要"},
            headers=author_headers,
        )
        after = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()
        assert after["updated_at"] > before["updated_at"]

    async def test_missing_article_returns_404(self, client: AsyncClient) -> None:
        assert (await client.get("/api/v1/articles/no-such-slug")).status_code == 404

    async def test_draft_is_404_for_guest_but_visible_to_author(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """草稿对访客返回 404 而非 403——403 等于承认"这里有一篇未发布的文章"。"""
        draft = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(status="draft"),
                headers=author_headers,
            )
        ).json()

        assert (await client.get(f"/api/v1/articles/{draft['slug']}")).status_code == 404
        owned = await client.get(f"/api/v1/articles/{draft['slug']}", headers=author_headers)
        assert owned.status_code == 200
        assert owned.json()["status"] == "draft"

    async def test_neighbors_follow_publish_order(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """prev 是更早发布的一篇，next 是更新的一篇，两端为 None。"""
        ids = []
        for index in range(3):
            body = (
                await client.post(
                    "/api/v1/articles",
                    json=make_article_payload(title=f"相邻文章{index}-{unique_suffix()}"),
                    headers=author_headers,
                )
            ).json()
            ids.append(body["id"])

        oldest = (await client.get(f"/api/v1/articles/{ids[0]}")).json()
        assert oldest["prev"] is None
        assert oldest["next"]["id"] == ids[1]

        middle = (await client.get(f"/api/v1/articles/{ids[1]}")).json()
        assert middle["prev"]["id"] == ids[0]
        assert middle["next"]["id"] == ids[2]

        newest = (await client.get(f"/api/v1/articles/{ids[2]}")).json()
        assert newest["prev"]["id"] == ids[1]
        assert newest["next"] is None

    async def test_draft_never_appears_as_neighbor(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """中间插一篇草稿，前后两篇已发布文章应该直接互为邻居。"""
        first = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=author_headers
            )
        ).json()
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(status="draft"),
            headers=author_headers,
        )
        third = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=author_headers
            )
        ).json()

        detail = (await client.get(f"/api/v1/articles/{third['id']}")).json()
        assert detail["prev"]["id"] == first["id"]


class TestUpdateAndDelete:
    async def test_partial_update_keeps_other_fields(
        self, client: AsyncClient, author_headers: dict[str, str], published_article: dict
    ) -> None:
        response = await client.patch(
            f"/api/v1/articles/{published_article['id']}",
            json={"title": "只改标题"},
            headers=author_headers,
        )
        assert response.status_code == 200
        body = response.json()
        assert body["title"] == "只改标题"
        # slug 不变：已发布文章的 URL 一旦变化，外链与收录全部作废
        assert body["slug"] == published_article["slug"]
        assert body["content_md"] == published_article["content_md"]

    async def test_explicit_slug_change_works(
        self, client: AsyncClient, author_headers: dict[str, str], published_article: dict
    ) -> None:
        body = (
            await client.patch(
                f"/api/v1/articles/{published_article['id']}",
                json={"slug": "brand-new-slug"},
                headers=author_headers,
            )
        ).json()
        assert body["slug"] == "brand-new-slug"

    async def test_nullable_field_can_be_cleared(
        self, client: AsyncClient, author_headers: dict[str, str], published_article: dict
    ) -> None:
        """摘要要能被清空。用 exclude_unset 区分"没传"和"传了 null"。"""
        body = (
            await client.patch(
                f"/api/v1/articles/{published_article['id']}",
                json={"summary": None},
                headers=author_headers,
            )
        ).json()
        assert body["summary"] is None

    async def test_publishing_a_draft_sets_published_at(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        draft = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(status="draft"),
                headers=author_headers,
            )
        ).json()
        published = (
            await client.patch(
                f"/api/v1/articles/{draft['id']}",
                json={"status": "published"},
                headers=author_headers,
            )
        ).json()
        assert published["published_at"] is not None

    async def test_republish_does_not_reset_published_at(
        self, client: AsyncClient, author_headers: dict[str, str], published_article: dict
    ) -> None:
        """反复切换状态不能刷新发布时间，否则"最新文章"排序会被玩坏。"""
        original = published_article["published_at"]
        again = (
            await client.patch(
                f"/api/v1/articles/{published_article['id']}",
                json={"status": "published"},
                headers=author_headers,
            )
        ).json()
        assert again["published_at"] == original

    async def test_author_cannot_edit_others_article(
        self,
        client: AsyncClient,
        admin_headers: dict[str, str],
        author_headers: dict[str, str],
    ) -> None:
        admin_article = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=admin_headers
            )
        ).json()
        response = await client.patch(
            f"/api/v1/articles/{admin_article['id']}",
            json={"title": "越权改标题"},
            headers=author_headers,
        )
        assert response.status_code == 403

    async def test_admin_can_edit_any_article(
        self,
        client: AsyncClient,
        admin_headers: dict[str, str],
        published_article: dict,
    ) -> None:
        response = await client.patch(
            f"/api/v1/articles/{published_article['id']}",
            json={"title": "站长来改"},
            headers=admin_headers,
        )
        assert response.status_code == 200

    async def test_author_cannot_delete_others_article(
        self,
        client: AsyncClient,
        admin_headers: dict[str, str],
        author_headers: dict[str, str],
    ) -> None:
        admin_article = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=admin_headers
            )
        ).json()
        response = await client.delete(
            f"/api/v1/articles/{admin_article['id']}", headers=author_headers
        )
        assert response.status_code == 403

    async def test_delete_removes_article(
        self, client: AsyncClient, author_headers: dict[str, str], published_article: dict
    ) -> None:
        response = await client.delete(
            f"/api/v1/articles/{published_article['id']}", headers=author_headers
        )
        assert response.status_code == 204
        assert (
            await client.get(f"/api/v1/articles/{published_article['slug']}")
        ).status_code == 404

    async def test_update_missing_article_404(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        response = await client.patch(
            "/api/v1/articles/999999", json={"title": "x"}, headers=author_headers
        )
        assert response.status_code == 404


class TestLike:
    async def test_like_increments_count(
        self, client: AsyncClient, published_article: dict
    ) -> None:
        before = published_article["like_count"]
        response = await client.post(f"/api/v1/articles/{published_article['id']}/like")
        assert response.status_code == 200
        assert response.json()["like_count"] == before + 1

    async def test_like_missing_article_404(self, client: AsyncClient) -> None:
        assert (await client.post("/api/v1/articles/999999/like")).status_code == 404

    async def test_cannot_like_a_draft(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        draft = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(status="draft"),
                headers=author_headers,
            )
        ).json()
        response = await client.post(f"/api/v1/articles/{draft['id']}/like")
        assert response.status_code == 404

    async def test_cannot_like_an_archived_article(
        self,
        client: AsyncClient,
        published_article: dict,
        author_headers: dict[str, str],
    ) -> None:
        """归档文章详情仍可达，但不再接受点赞——与浏览计数「仅已发布累计」同口径。"""
        archived = await client.patch(
            f"/api/v1/articles/{published_article['id']}",
            json={"status": "archived"},
            headers=author_headers,
        )
        assert archived.status_code == 200
        assert (
            await client.post(f"/api/v1/articles/{published_article['id']}/like")
        ).status_code == 400


class TestArchive:
    async def test_archive_groups_by_month(
        self, client: AsyncClient, published_article: dict
    ) -> None:
        groups = (await client.get("/api/v1/articles/archive")).json()
        assert len(groups) == 1
        assert len(groups[0]["year_month"]) == 7  # YYYY-MM
        assert groups[0]["count"] == 1
        assert groups[0]["items"][0]["id"] == published_article["id"]

    async def test_archive_hides_drafts(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(status="draft"),
            headers=author_headers,
        )
        assert (await client.get("/api/v1/articles/archive")).json() == []

    def test_year_month_validator(self) -> None:
        """纯函数单测：``2026-13`` 这种看似合法的输入必须被拦住。"""
        from app.services.article_service import _is_year_month

        assert _is_year_month("2026-09")
        assert _is_year_month("2026-12")
        assert not _is_year_month("2026-13")
        assert not _is_year_month("2026-00")
        assert not _is_year_month("2026-9")
        assert not _is_year_month("202609")
        assert not _is_year_month("abcd-09")


class TestCoverVariants:
    """封面多尺寸变体装配：创建响应 / 列表 / 详情 / 相关文章口径一致。"""

    async def test_create_list_detail_carry_cover_variants(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        upload = (
            await client.post(
                "/api/v1/attachments/upload",
                files={"file": ("cover.png", make_png_bytes((1920, 1080)), "image/png")},
                headers=author_headers,
            )
        ).json()
        created = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(cover_image=upload["url"]),
                headers=author_headers,
            )
        ).json()
        assert [v["width"] for v in created["cover_variants"]] == [480, 800, 1600]

        listing = (await client.get("/api/v1/articles")).json()
        item = next(i for i in listing["items"] if i["id"] == created["id"])
        assert [v["width"] for v in item["cover_variants"]] == [480, 800, 1600]

        detail = (await client.get(f"/api/v1/articles/{created['slug']}")).json()
        assert [v["width"] for v in detail["cover_variants"]] == [480, 800, 1600]

    async def test_external_cover_falls_back_to_empty_variants(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """外链封面查不到附件记录，静默落空列表而不是报错。"""
        created = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(cover_image="https://example.com/pic.jpg"),
                headers=author_headers,
            )
        ).json()
        assert created["cover_variants"] == []

    async def test_related_articles_carry_cover_variants(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        upload = (
            await client.post(
                "/api/v1/attachments/upload",
                files={"file": ("rel.png", make_png_bytes((1920, 1080)), "image/png")},
                headers=author_headers,
            )
        ).json()
        first = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(tags=["共享标签"]),
                headers=author_headers,
            )
        ).json()
        second = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(tags=["共享标签"], cover_image=upload["url"]),
                headers=author_headers,
            )
        ).json()

        related = (await client.get(f"/api/v1/articles/{first['id']}/related")).json()
        entry = next(i for i in related if i["id"] == second["id"])
        assert [v["width"] for v in entry["cover_variants"]] == [480, 800, 1600]
