"""文章模块测试：创建/列表/分页/排序/筛选/详情/权限/点赞/上下篇。"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from datetime import UTC, datetime, timedelta

from httpx import AsyncClient
from sqlalchemy import event, select

from tests.factories import make_article_payload, make_png_bytes, unique_suffix


@contextmanager
def _captured_statements() -> Iterator[list[str]]:
    """捕获上下文里真正发到数据库的 SQL 文本。

    断言"列表没有 select 正文"只能落在**实际执行的语句**上：响应体里本来就没有
    ``content_md`` 字段（``ArticleSummary`` 不含它），断言响应等于什么都没测。
    挂在 engine 上而不是会话上，是因为语句在 ORM 编译缓存之后才成形——
    这里拿到的就是最终 SQL。
    """
    from app.db.session import engine

    statements: list[str] = []

    def _record(conn: object, cursor: object, statement: str, *args: object) -> None:
        statements.append(statement)

    event.listen(engine.sync_engine, "before_cursor_execute", _record)
    try:
        yield statements
    finally:
        event.remove(engine.sync_engine, "before_cursor_execute", _record)


def _article_selects(statements: list[str]) -> list[str]:
    """从捕获结果里挑出对 articles 表的 SELECT。"""
    return [
        statement
        for statement in statements
        if statement.lstrip().upper().startswith("SELECT") and "FROM articles" in statement
    ]


class TestCreate:
    async def test_create_draft_has_no_published_at(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        response = await client.post(
            "/api/v1/articles",
            json=make_article_payload(status="draft"),
            headers=author_headers,
        )
        assert response.status_code == 201
        body = response.json()
        assert body["status"] == "draft"
        assert body["published_at"] is None

    async def test_create_published_sets_published_at(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        body = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=author_headers
            )
        ).json()
        assert body["status"] == "published"
        assert body["published_at"] is not None

    async def test_summary_and_reading_time_are_derived(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """不传 summary 时从正文自动抽取；阅读时长按正文长度估算。"""
        body = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(summary=None, content_md="# 标题\n\n" + "内容" * 800),
                headers=author_headers,
            )
        ).json()
        assert body["summary"]
        assert "内容" in body["summary"]
        assert body["reading_time"] >= 1

    async def test_slug_autogenerated_and_unique(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        title = f"重名标题-{unique_suffix()}"
        first = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(title=title), headers=author_headers
            )
        ).json()
        second = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(title=title), headers=author_headers
            )
        ).json()
        assert first["slug"] != second["slug"]
        assert second["slug"].endswith("-2")

    async def test_custom_slug_is_respected(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        body = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(slug="my-custom-slug"),
                headers=author_headers,
            )
        ).json()
        assert body["slug"] == "my-custom-slug"

    async def test_guest_cannot_create(self, client: AsyncClient) -> None:
        response = await client.post("/api/v1/articles", json=make_article_payload())
        assert response.status_code == 401

    async def test_unknown_category_is_rejected(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        response = await client.post(
            "/api/v1/articles",
            json=make_article_payload(category_id=999999),
            headers=author_headers,
        )
        assert response.status_code == 400

    async def test_too_many_tags_rejected(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        response = await client.post(
            "/api/v1/articles",
            json=make_article_payload(tags=[f"标签{i}" for i in range(12)]),
            headers=author_headers,
        )
        assert response.status_code == 422

    async def test_tags_are_created_on_the_fly(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """打一个新标签不该要求先去标签页创建——自由打标签是写作体验的一部分。"""
        name = f"新标签{unique_suffix()}"
        body = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(tags=[name, name]),
                headers=author_headers,
            )
        ).json()
        assert [tag["name"] for tag in body["tags"]] == [name]  # 去重后只剩一个


class TestListAndPagination:
    async def test_pagination_math(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        for _ in range(5):
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=author_headers
            )

        first = (await client.get("/api/v1/articles?page=1&page_size=2")).json()
        assert first["total"] == 5
        assert first["pages"] == 3
        assert len(first["items"]) == 2

        last = (await client.get("/api/v1/articles?page=3&page_size=2")).json()
        assert len(last["items"]) == 1

    async def test_out_of_range_page_keeps_correct_total(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """页码超界时前端要能拿到 total 才知道该弹回第几页，不能直接返回 0。"""
        await client.post("/api/v1/articles", json=make_article_payload(), headers=author_headers)
        body = (await client.get("/api/v1/articles?page=99&page_size=10")).json()
        assert body["total"] == 1
        assert body["items"] == []

    async def test_page_size_upper_bound_enforced(self, client: AsyncClient) -> None:
        response = await client.get("/api/v1/articles?page_size=100000")
        assert response.status_code == 422

    async def test_invalid_page_rejected(self, client: AsyncClient) -> None:
        assert (await client.get("/api/v1/articles?page=0")).status_code == 422

    async def test_list_excludes_content_md(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """列表接口绝不能带正文——这是分页接口最常见的性能事故来源。"""
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(content_md="# 标题\n\n" + "很长很长的正文。" * 500),
            headers=author_headers,
        )
        body = (await client.get("/api/v1/articles")).json()
        assert body["items"]
        assert "content_md" not in body["items"][0]
        assert "comment_count" in body["items"][0]

    async def test_draft_not_in_public_list(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(status="draft"),
            headers=author_headers,
        )
        body = (await client.get("/api/v1/articles")).json()
        assert body["total"] == 0

    async def test_managed_list_shows_own_drafts(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(status="draft"),
            headers=author_headers,
        )
        body = (await client.get("/api/v1/articles/manage/list", headers=author_headers)).json()
        assert body["total"] == 1
        assert body["items"][0]["status"] == "draft"

    async def test_author_managed_list_hides_others_articles(
        self, client: AsyncClient, admin_headers: dict[str, str], author_headers: dict[str, str]
    ) -> None:
        """作者后台只能看自己的——这是默认的保守策略，不需要额外配置。"""
        await client.post("/api/v1/articles", json=make_article_payload(), headers=admin_headers)
        body = (await client.get("/api/v1/articles/manage/list", headers=author_headers)).json()
        assert body["total"] == 0

        admin_view = (
            await client.get("/api/v1/articles/manage/list", headers=admin_headers)
        ).json()
        assert admin_view["total"] == 1


class TestSorting:
    async def _seed_three(self, client: AsyncClient, headers: dict[str, str]) -> None:
        titles = ["第一篇", "第二篇", "第三篇"]
        for index, title in enumerate(titles):
            body = (
                await client.post(
                    "/api/v1/articles",
                    json=make_article_payload(title=title),
                    headers=headers,
                )
            ).json()
            # 用 PATCH 调整阅读量，构造"热度与时间顺序不同"的场景
            if index == 0:
                for _ in range(3):
                    await client.post(f"/api/v1/articles/{body['id']}/like")

    async def test_latest_and_oldest_are_mirror_images(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        await self._seed_three(client, author_headers)
        latest = (await client.get("/api/v1/articles?sort=latest")).json()["items"]
        oldest = (await client.get("/api/v1/articles?sort=oldest")).json()["items"]
        assert [i["id"] for i in latest] == list(reversed([i["id"] for i in oldest]))

    async def test_hottest_sorts_by_view_count(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        ids = []
        for index in range(3):
            body = (
                await client.post(
                    "/api/v1/articles",
                    json=make_article_payload(title=f"热度文章{index}"),
                    headers=author_headers,
                )
            ).json()
            ids.append(body["id"])
        # 给最后一篇（时间上最新）刷最多的阅读量
        for _ in range(3):
            await client.get(f"/api/v1/articles/{ids[-1]}")

        hottest = (await client.get("/api/v1/articles?sort=hottest")).json()["items"]
        assert hottest[0]["id"] == ids[-1]

    async def test_top_article_comes_first_regardless_of_sort(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """置顶的语义就是"永远在最前面"，否则置顶没有意义。"""
        normal = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=author_headers
            )
        ).json()
        pinned = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(is_top=True),
                headers=author_headers,
            )
        ).json()
        oldest_first = (await client.get("/api/v1/articles?sort=oldest")).json()["items"]
        assert oldest_first[0]["id"] == pinned["id"]
        assert oldest_first[1]["id"] == normal["id"]

    async def test_invalid_sort_enum_rejected(self, client: AsyncClient) -> None:
        response = await client.get("/api/v1/articles?sort=drop_table")
        assert response.status_code == 422


class TestFiltering:
    async def test_keyword_search_matches_title_and_body(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        token = unique_suffix()
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(title=f"包含关键词{token}的文章"),
            headers=author_headers,
        )
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(content_md=f"正文里也提到了 {token} 这个词"),
            headers=author_headers,
        )
        await client.post("/api/v1/articles", json=make_article_payload(), headers=author_headers)

        body = (await client.get(f"/api/v1/articles?keyword={token}")).json()
        assert body["total"] == 2

    async def test_like_wildcards_are_escaped(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """不转义的话，搜 `%` 会匹配到所有文章，这是个很隐蔽的 bug。"""
        await client.post("/api/v1/articles", json=make_article_payload(), headers=author_headers)
        body = (await client.get("/api/v1/articles?keyword=%25")).json()
        assert body["total"] == 0

    async def test_filter_by_tag_slug(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        tag = f"筛选标签{unique_suffix()}"
        created = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(tags=[tag]), headers=author_headers
            )
        ).json()
        slug = created["tags"][0]["slug"]
        body = (await client.get(f"/api/v1/articles?tag={slug}")).json()
        assert body["total"] == 1

    async def test_filter_by_category_slug_and_id(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        category = (
            await client.post(
                "/api/v1/categories",
                json={"name": f"分类{unique_suffix()}"},
                headers=author_headers,
            )
        ).json()
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(category_id=category["id"]),
            headers=author_headers,
        )
        by_slug = (await client.get(f"/api/v1/articles?category={category['slug']}")).json()
        by_id = (await client.get(f"/api/v1/articles?category={category['id']}")).json()
        assert by_slug["total"] == by_id["total"] == 1

    async def test_filter_by_author(
        self, client: AsyncClient, admin_headers: dict[str, str], author_id: int
    ) -> None:
        await client.post("/api/v1/articles", json=make_article_payload(), headers=admin_headers)
        body = (await client.get(f"/api/v1/articles?author_id={author_id}")).json()
        assert body["total"] == 0

    async def test_managed_list_filters_by_category_slug(
        self, client: AsyncClient, author_headers: dict[str, str], admin_headers: dict[str, str]
    ) -> None:
        """后台列表按 **slug** 筛选分类必须生效。

        回归用例：``list_managed`` 的两个分支原先只把 ``category_id`` 传进
        ``ArticleFilter``，漏了 ``category_slug``；而 ``build_article_filter`` 把
        非数字的 ``category`` 归到 slug 分支，于是 ``?category=<slug>``
        被静默丢弃 —— 返回全部文章且不报错，表现为「后台筛选时灵时不灵」
        （取决于前端传 slug 还是 id）。前台 ``/articles`` 一直是好的，所以只在
        后台暴露。
        """
        target = (
            await client.post(
                "/api/v1/categories",
                json={"name": f"目标分类{unique_suffix()}"},
                headers=author_headers,
            )
        ).json()
        other = (
            await client.post(
                "/api/v1/categories",
                json={"name": f"干扰分类{unique_suffix()}"},
                headers=author_headers,
            )
        ).json()
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(category_id=target["id"], status="draft"),
            headers=author_headers,
        )
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(category_id=other["id"], status="draft"),
            headers=author_headers,
        )

        # 不筛应当能同时看到两篇（确认数据确实都建出来了）
        all_managed = (
            await client.get("/api/v1/articles/manage/list", headers=admin_headers)
        ).json()
        assert all_managed["total"] == 2

        # slug 与 id 两条路径都要能筛（与前台 /articles 的口径一致）
        for admin in (True, False):
            headers = admin_headers if admin else author_headers
            by_slug = (
                await client.get(
                    f"/api/v1/articles/manage/list?category={target['slug']}", headers=headers
                )
            ).json()
            by_id = (
                await client.get(
                    f"/api/v1/articles/manage/list?category={target['id']}", headers=headers
                )
            ).json()

            assert by_slug["total"] == 1, f"slug 筛选失效（admin={admin}）"
            assert by_id["total"] == 1, f"id 筛选失效（admin={admin}）"


class TestDetail:
    async def test_detail_by_slug_and_id_are_equivalent(
        self, client: AsyncClient, published_article: dict[str, object]
    ) -> None:
        by_slug = await client.get(f"/api/v1/articles/{published_article['slug']}")
        by_id = await client.get(f"/api/v1/articles/{published_article['id']}")
        assert by_slug.status_code == by_id.status_code == 200
        assert by_slug.json()["id"] == by_id.json()["id"]
        assert by_slug.json()["content_md"] == published_article["content_md"]

    async def test_view_count_increments_via_dedicated_endpoint(
        self, client: AsyncClient, published_article: dict[str, object]
    ) -> None:
        """阅读计数改由 ``POST /articles/{id}/view`` 承担，返回最新值。

        为什么不再挂在详情 GET 上：详情响应体带每次 +1 的 ``view_count`` 时，
        基于响应体算的 ETag 必然每次都变，条件请求永远命中不了 304 ——
        计数与 HTTP 缓存不可兼得（见 ``get_article`` 的说明与
        ``test_detail_is_cacheable``）。
        """
        response = await client.post(f"/api/v1/articles/{published_article['id']}/view")

        assert response.status_code == 200, response.text
        assert response.json()["view_count"] == published_article["view_count"] + 1

        # 再记一次会继续累加（同一个访客重复打开文章就该算两次阅读）
        again = await client.post(f"/api/v1/articles/{published_article['id']}/view")
        assert again.json()["view_count"] == published_article["view_count"] + 2

    async def test_detail_get_does_not_touch_view_count(
        self, client: AsyncClient, published_article: dict[str, object]
    ) -> None:
        """详情 GET 是**纯读**：反复取内容，计数不动。

        这是"详情可缓存"的前提，也是与计数端点分工的边界。
        """
        first = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()
        second = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()

        assert first["view_count"] == published_article["view_count"]
        assert second["view_count"] == published_article["view_count"]

    async def test_view_endpoint_rejects_missing_and_draft(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """不存在的文章 404；草稿也不计阅读数（连作者预览都不算）。"""
        assert (await client.post("/api/v1/articles/999999/view")).status_code == 404

        draft = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(status="draft"),
                headers=author_headers,
            )
        ).json()
        assert (await client.post(f"/api/v1/articles/{draft['id']}/view")).status_code == 404

    async def test_detail_is_cacheable_and_revalidates_to_304(
        self, client: AsyncClient, published_article: dict[str, object]
    ) -> None:
        """**详情页必须真能命中 304**——这是本组改动的最终目的。

        实测过反例：计数留在详情 GET 里时，连续两次请求的 ETag 一定不同、
        ``If-None-Match`` 一律返回 200（``max-age=60`` 完全没用）。

        现在详情是**纯读**：GET 不再改动任何参与响应体的字段，所以 ETag 在
        "内容不变"期间是稳定的 —— 这正是缓存成立的定义。计数端点会带来
        **一次**变化（``view_count`` 从旧值到新值），之后一直稳定；
        这与真实浏览时序一致（进页面 → 计数 → 之后重复校验）。
        """
        url = f"/api/v1/articles/{published_article['slug']}"
        article_id = published_article["id"]

        # 先走一次计数：真实访问的第一步，让响应体落到"当前值"上
        counted = await client.post(f"/api/v1/articles/{article_id}/view")
        assert counted.status_code == 200
        settled = counted.json()["view_count"]

        first = await client.get(url)
        assert first.status_code == 200
        etag = first.headers.get("etag")
        assert etag, "公开读接口应当带 ETag"
        assert "max-age" in first.headers.get("cache-control", "")
        assert first.json()["view_count"] == settled

        # 关键：详情 GET 自己**不会**再改变响应体（真实浏览器里就是重复打开同一页）
        again = await client.get(url)
        assert again.content == first.content, "详情 GET 是纯读，响应体必须逐字相同"

        second = await client.get(url, headers={"If-None-Match": etag})
        assert second.status_code == 304, (
            f"条件请求未命中 304（实际 {second.status_code}）：详情响应体在变化，"
            "ETag 永远失效 —— 检查有没有把会自增的字段放回 GET 路径"
        )
        assert not second.content, "304 不能带响应体"

        # 再浏览一次：计数确实变了，但那只是一次新的浏览，缓存随后照常重新稳定
        after_view = await client.post(f"/api/v1/articles/{article_id}/view")
        assert after_view.json()["view_count"] == settled + 1
        refreshed = await client.get(url)
        assert refreshed.json()["view_count"] == settled + 1
        assert (
            await client.get(url, headers={"If-None-Match": refreshed.headers["etag"]})
        ).status_code == 304

    async def test_view_does_not_touch_updated_at(
        self, client: AsyncClient, published_article: dict[str, object]
    ) -> None:
        """阅读量变化不是内容修改，不能改 updated_at。

        列上的 ``onupdate`` 对 Core ``update()`` 同样生效，早先没显式钉住它，
        于是**读一次文章就改一次 updated_at**。后果有两个，都是用户可见的：
        后台默认排序 ``sort=updated`` 实际变成「最近被看过的」，热门旧文会压过
        刚编辑过的；sitemap 的 ``<lastmod>`` 每次访问都变，等于告诉爬虫
        全站天天在改。
        """
        before = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()

        first = await client.post(f"/api/v1/articles/{published_article['id']}/view")
        assert first.json()["view_count"] == published_article["view_count"] + 1

        # 再记几次，updated_at 必须纹丝不动
        for _ in range(2):
            await client.post(f"/api/v1/articles/{published_article['id']}/view")
        later = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()
        assert later["view_count"] == published_article["view_count"] + 3
        assert later["updated_at"] == before["updated_at"]

    async def test_like_does_not_touch_updated_at(
        self, client: AsyncClient, published_article: dict[str, object]
    ) -> None:
        """点赞同理：计数变化不该被当成内容更新。"""
        before = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()
        await client.post(f"/api/v1/articles/{published_article['id']}/like")
        after = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()
        assert after["updated_at"] == before["updated_at"]

    async def test_editing_does_touch_updated_at(
        self,
        client: AsyncClient,
        published_article: dict[str, object],
        author_headers: dict[str, str],
    ) -> None:
        """反向断言：真正的内容修改必须更新 updated_at，别修过头。"""
        before = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()
        await client.patch(
            f"/api/v1/articles/{published_article['id']}",
            json={"summary": "改过的摘要"},
            headers=author_headers,
        )
        after = (await client.get(f"/api/v1/articles/{published_article['slug']}")).json()
        assert after["updated_at"] > before["updated_at"]

    async def test_missing_article_returns_404(self, client: AsyncClient) -> None:
        assert (await client.get("/api/v1/articles/no-such-slug")).status_code == 404

    async def test_draft_is_404_for_guest_but_visible_to_author(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """草稿对访客返回 404 而非 403——403 等于承认"这里有一篇未发布的文章"。"""
        draft = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(status="draft"),
                headers=author_headers,
            )
        ).json()

        assert (await client.get(f"/api/v1/articles/{draft['slug']}")).status_code == 404
        owned = await client.get(f"/api/v1/articles/{draft['slug']}", headers=author_headers)
        assert owned.status_code == 200
        assert owned.json()["status"] == "draft"

    async def test_neighbors_follow_publish_order(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """prev 是更早发布的一篇，next 是更新的一篇，两端为 None。"""
        ids = []
        for index in range(3):
            body = (
                await client.post(
                    "/api/v1/articles",
                    json=make_article_payload(title=f"相邻文章{index}-{unique_suffix()}"),
                    headers=author_headers,
                )
            ).json()
            ids.append(body["id"])

        oldest = (await client.get(f"/api/v1/articles/{ids[0]}")).json()
        assert oldest["prev"] is None
        assert oldest["next"]["id"] == ids[1]

        middle = (await client.get(f"/api/v1/articles/{ids[1]}")).json()
        assert middle["prev"]["id"] == ids[0]
        assert middle["next"]["id"] == ids[2]

        newest = (await client.get(f"/api/v1/articles/{ids[2]}")).json()
        assert newest["prev"]["id"] == ids[1]
        assert newest["next"] is None

    async def test_draft_never_appears_as_neighbor(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """中间插一篇草稿，前后两篇已发布文章应该直接互为邻居。"""
        first = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=author_headers
            )
        ).json()
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(status="draft"),
            headers=author_headers,
        )
        third = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=author_headers
            )
        ).json()

        detail = (await client.get(f"/api/v1/articles/{third['id']}")).json()
        assert detail["prev"]["id"] == first["id"]


class TestUpdateAndDelete:
    async def test_partial_update_keeps_other_fields(
        self, client: AsyncClient, author_headers: dict[str, str], published_article: dict
    ) -> None:
        response = await client.patch(
            f"/api/v1/articles/{published_article['id']}",
            json={"title": "只改标题"},
            headers=author_headers,
        )
        assert response.status_code == 200
        body = response.json()
        assert body["title"] == "只改标题"
        # slug 不变：已发布文章的 URL 一旦变化，外链与收录全部作废
        assert body["slug"] == published_article["slug"]
        assert body["content_md"] == published_article["content_md"]

    async def test_explicit_slug_change_works(
        self, client: AsyncClient, author_headers: dict[str, str], published_article: dict
    ) -> None:
        body = (
            await client.patch(
                f"/api/v1/articles/{published_article['id']}",
                json={"slug": "brand-new-slug"},
                headers=author_headers,
            )
        ).json()
        assert body["slug"] == "brand-new-slug"

    async def test_nullable_field_can_be_cleared(
        self, client: AsyncClient, author_headers: dict[str, str], published_article: dict
    ) -> None:
        """摘要要能被清空。用 exclude_unset 区分"没传"和"传了 null"。"""
        body = (
            await client.patch(
                f"/api/v1/articles/{published_article['id']}",
                json={"summary": None},
                headers=author_headers,
            )
        ).json()
        assert body["summary"] is None

    async def test_publishing_a_draft_sets_published_at(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        draft = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(status="draft"),
                headers=author_headers,
            )
        ).json()
        published = (
            await client.patch(
                f"/api/v1/articles/{draft['id']}",
                json={"status": "published"},
                headers=author_headers,
            )
        ).json()
        assert published["published_at"] is not None

    async def test_republish_does_not_reset_published_at(
        self, client: AsyncClient, author_headers: dict[str, str], published_article: dict
    ) -> None:
        """反复切换状态不能刷新发布时间，否则"最新文章"排序会被玩坏。"""
        original = published_article["published_at"]
        again = (
            await client.patch(
                f"/api/v1/articles/{published_article['id']}",
                json={"status": "published"},
                headers=author_headers,
            )
        ).json()
        assert again["published_at"] == original

    async def test_author_cannot_edit_others_article(
        self,
        client: AsyncClient,
        admin_headers: dict[str, str],
        author_headers: dict[str, str],
    ) -> None:
        admin_article = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=admin_headers
            )
        ).json()
        response = await client.patch(
            f"/api/v1/articles/{admin_article['id']}",
            json={"title": "越权改标题"},
            headers=author_headers,
        )
        assert response.status_code == 403

    async def test_admin_can_edit_any_article(
        self,
        client: AsyncClient,
        admin_headers: dict[str, str],
        published_article: dict,
    ) -> None:
        response = await client.patch(
            f"/api/v1/articles/{published_article['id']}",
            json={"title": "站长来改"},
            headers=admin_headers,
        )
        assert response.status_code == 200

    async def test_author_cannot_delete_others_article(
        self,
        client: AsyncClient,
        admin_headers: dict[str, str],
        author_headers: dict[str, str],
    ) -> None:
        admin_article = (
            await client.post(
                "/api/v1/articles", json=make_article_payload(), headers=admin_headers
            )
        ).json()
        response = await client.delete(
            f"/api/v1/articles/{admin_article['id']}", headers=author_headers
        )
        assert response.status_code == 403

    async def test_delete_removes_article(
        self, client: AsyncClient, author_headers: dict[str, str], published_article: dict
    ) -> None:
        response = await client.delete(
            f"/api/v1/articles/{published_article['id']}", headers=author_headers
        )
        assert response.status_code == 204
        assert (
            await client.get(f"/api/v1/articles/{published_article['slug']}")
        ).status_code == 404

    async def test_update_missing_article_404(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        response = await client.patch(
            "/api/v1/articles/999999", json={"title": "x"}, headers=author_headers
        )
        assert response.status_code == 404


class TestLike:
    async def test_like_increments_count(
        self, client: AsyncClient, published_article: dict
    ) -> None:
        before = published_article["like_count"]
        response = await client.post(f"/api/v1/articles/{published_article['id']}/like")
        assert response.status_code == 200
        assert response.json()["like_count"] == before + 1

    async def test_like_missing_article_404(self, client: AsyncClient) -> None:
        assert (await client.post("/api/v1/articles/999999/like")).status_code == 404

    async def test_cannot_like_a_draft(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        draft = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(status="draft"),
                headers=author_headers,
            )
        ).json()
        response = await client.post(f"/api/v1/articles/{draft['id']}/like")
        assert response.status_code == 404

    async def test_cannot_like_an_archived_article(
        self,
        client: AsyncClient,
        published_article: dict,
        author_headers: dict[str, str],
    ) -> None:
        """归档文章详情仍可达，但不再接受点赞——与浏览计数「仅已发布累计」同口径。"""
        archived = await client.patch(
            f"/api/v1/articles/{published_article['id']}",
            json={"status": "archived"},
            headers=author_headers,
        )
        assert archived.status_code == 200
        assert (
            await client.post(f"/api/v1/articles/{published_article['id']}/like")
        ).status_code == 400


class TestArchive:
    async def test_archive_groups_by_month(
        self, client: AsyncClient, published_article: dict
    ) -> None:
        groups = (await client.get("/api/v1/articles/archive")).json()
        assert len(groups) == 1
        assert len(groups[0]["year_month"]) == 7  # YYYY-MM
        assert groups[0]["count"] == 1
        assert groups[0]["items"][0]["id"] == published_article["id"]

    async def test_archive_hides_drafts(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        await client.post(
            "/api/v1/articles",
            json=make_article_payload(status="draft"),
            headers=author_headers,
        )
        assert (await client.get("/api/v1/articles/archive")).json() == []

    def test_year_month_validator(self) -> None:
        """纯函数单测：``2026-13`` 这种看似合法的输入必须被拦住。"""
        from app.services.article_service import _is_year_month

        assert _is_year_month("2026-09")
        assert _is_year_month("2026-12")
        assert not _is_year_month("2026-13")
        assert not _is_year_month("2026-00")
        assert not _is_year_month("2026-9")
        assert not _is_year_month("202609")
        assert not _is_year_month("abcd-09")

    async def test_month_comes_from_published_at_not_created_at(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """补发一篇「去年写的」文章：归到**发布时间**那个月，而不是 created_at 当月。

        这是 ``published_ym`` 派生规则的核心语义（``coalesce(published_at,
        created_at)``），也是迁移回填与新写入两条路径必须一致的地方。
        """
        created = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(
                    published_at=datetime(2024, 3, 15, 8, 30, tzinfo=UTC).isoformat()
                ),
                headers=author_headers,
            )
        ).json()
        assert created["published_at"].startswith("2024-03")

        groups = (await client.get("/api/v1/articles/archive")).json()
        assert [group["year_month"] for group in groups] == ["2024-03"]
        assert groups[0]["items"][0]["id"] == created["id"]

    async def test_publishing_a_draft_uses_its_published_at_month(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """草稿发布：先记在 created_at 当月，改状态后必须迁到 published_at 那个月。

        走的是 ``ArticleCommandService.update`` 那条写路径。派生列如果只在 INSERT
        时算一次，这里就会停在草稿的月份上——归档页"永远少一篇/多一篇"，
        而且不会报任何错。
        """
        draft = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(status="draft"),
                headers=author_headers,
            )
        ).json()
        assert (await client.get("/api/v1/articles/archive")).json() == []

        patched = await client.patch(
            f"/api/v1/articles/{draft['id']}",
            json={
                "status": "published",
                "published_at": datetime(2025, 1, 15, 9, 0, tzinfo=UTC).isoformat(),
            },
            headers=author_headers,
        )
        assert patched.status_code == 200, patched.text

        groups = (await client.get("/api/v1/articles/archive")).json()
        assert [group["year_month"] for group in groups] == ["2025-01"]
        assert [item["id"] for item in groups[0]["items"]] == [draft["id"]]

    async def test_scheduled_article_shows_under_its_scheduled_month(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """定时发布：归档月份按**排期时间**算，不是创建时间。"""
        target = datetime.now(UTC) + timedelta(days=40)
        created = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(published_at=target.isoformat()),
                headers=author_headers,
            )
        ).json()

        groups = (await client.get("/api/v1/articles/archive")).json()
        assert [group["year_month"] for group in groups] == [target.strftime("%Y-%m")]
        assert groups[0]["items"][0]["id"] == created["id"]

    async def test_rescheduling_moves_the_article_between_months(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """改发布时间（改期）后，归档月份必须跟着走。"""
        created = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(
                    published_at=datetime(2024, 5, 5, 10, 0, tzinfo=UTC).isoformat()
                ),
                headers=author_headers,
            )
        ).json()
        assert [g["year_month"] for g in (await client.get("/api/v1/articles/archive")).json()] == [
            "2024-05"
        ]

        patched = await client.patch(
            f"/api/v1/articles/{created['id']}",
            json={"published_at": datetime(2024, 6, 5, 10, 0, tzinfo=UTC).isoformat()},
            headers=author_headers,
        )
        assert patched.status_code == 200, patched.text

        groups = (await client.get("/api/v1/articles/archive")).json()
        assert [group["year_month"] for group in groups] == ["2024-06"]
        assert [item["id"] for item in groups[0]["items"]] == [created["id"]]


class TestPublishedYmColumn:
    """派生列本身（而不是 API 的表现）：草稿也必须带月份。

    迁移回填对**所有**存量行按 ``coalesce(published_at, created_at)`` 算月份，
    写路径如果只覆盖 ``published_at``，新草稿就会是 NULL——老行有值、新行没有，
    这种漂移不报错，只会在"想按草稿月份做点什么"时突然暴露。
    """

    async def test_draft_row_falls_back_to_created_at_month(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        from app.db.session import async_session_factory
        from app.models import Article

        draft = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(status="draft"),
                headers=author_headers,
            )
        ).json()

        async with async_session_factory() as session:
            row = (
                await session.execute(
                    select(Article.published_ym, Article.created_at).where(
                        Article.id == draft["id"]
                    )
                )
            ).one()

        assert row.published_ym == row.created_at.strftime("%Y-%m")

    async def test_only_publish_time_edits_recompute_the_column(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """改标题/正文不该动这一列——它只由发布时间决定。"""
        from app.db.session import async_session_factory
        from app.models import Article

        created = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(
                    published_at=datetime(2024, 7, 7, 7, 0, tzinfo=UTC).isoformat()
                ),
                headers=author_headers,
            )
        ).json()

        patched = await client.patch(
            f"/api/v1/articles/{created['id']}",
            json={"title": "换了标题", "content_md": "换了正文"},
            headers=author_headers,
        )
        assert patched.status_code == 200, patched.text

        async with async_session_factory() as session:
            stored = (
                await session.execute(
                    select(Article.published_ym).where(Article.id == created["id"])
                )
            ).scalar_one()

        assert stored == "2024-07"


class TestListProjection:
    """列表接口不得把正文（``content_md``）搬进进程再丢掉。

    断言落在**真正发出去的 SQL** 上：响应体里本来就没有这个字段
    （``ArticleSummary`` 不含它），只断言响应等于什么都没测。
    """

    async def test_list_sql_does_not_select_content_md(
        self,
        client: AsyncClient,
        author_headers: dict[str, str],
        admin_headers: dict[str, str],
    ) -> None:
        created = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(content_md="# 正文\n\n" + "正文内容" * 2000),
                headers=author_headers,
            )
        ).json()

        with _captured_statements() as public_statements:
            public = await client.get("/api/v1/articles?page_size=50")
        with _captured_statements() as managed_statements:
            managed = await client.get(
                "/api/v1/articles/manage/list?page_size=50", headers=admin_headers
            )

        assert public.status_code == 200, public.text
        assert managed.status_code == 200, managed.text
        assert any(item["id"] == created["id"] for item in managed.json()["items"])

        for label, statements in (
            ("前台列表", public_statements),
            ("后台列表", managed_statements),
        ):
            selects = _article_selects(statements)
            assert selects, f"{label}没有捕获到 articles 的 SELECT，用例前提不成立"
            offenders = [sql for sql in selects if "content_md" in sql]
            assert not offenders, f"{label}仍然在 select 正文：\n{offenders[0]}"

        # 投影没有把列表需要的列裁掉：字段齐全（少一列会在序列化时炸/丢字段）
        item = next(i for i in managed.json()["items"] if i["id"] == created["id"])
        assert item["title"] and item["summary"] and item["tags"]
        assert {"status", "view_count", "reading_time", "created_at", "updated_at"} <= set(item)

        # 反向对照：详情接口**必须**照旧加载正文。它同时证明捕获机制能看到
        # content_md —— 否则上面两条断言可能只是"什么都没捕到"而假通过。
        with _captured_statements() as detail_statements:
            detail = await client.get(f"/api/v1/articles/{created['slug']}")
        assert detail.status_code == 200, detail.text
        assert detail.json()["content_md"]
        assert any("content_md" in sql for sql in _article_selects(detail_statements)), (
            "详情接口的 SQL 里没有 content_md —— 捕获方式失效，列表那两条断言不可信"
        )

    async def test_rss_still_gets_the_body_for_its_summary_fallback(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """RSS 的 ``description`` 在 summary 为空时要回退到正文。

        ``load_only`` 之后被延迟加载的列在**异步会话**里访问会抛 ``MissingGreenlet``，
        所以"谁需要正文"必须由调用方显式声明：``FeedService._latest`` 用的是
        ``list_paged`` 的默认值（整行），这条用例把它钉住 —— 默认值哪天被改成
        ``False``，这里会红，而不是上线后 ``/feed.xml`` 静默 500。
        """
        marker = f"回退标记{unique_suffix()}"
        created = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(content_md=f"# 标题\n\n{marker}"),
                headers=author_headers,
            )
        ).json()
        # summary 是允许被显式清空的字段（NULLABLE_FIELDS），清空后 RSS 只剩正文可退回
        cleared = await client.patch(
            f"/api/v1/articles/{created['id']}", json={"summary": None}, headers=author_headers
        )
        assert cleared.status_code == 200, cleared.text
        assert cleared.json()["summary"] is None, "summary 没被清空，用例前提不成立"

        feed = await client.get("/feed.xml")
        assert feed.status_code == 200, feed.text
        assert marker in feed.text, "RSS 没能回退到正文：content_md 没有被加载"


class TestCoverVariants:
    """封面多尺寸变体装配：创建响应 / 列表 / 详情 / 相关文章口径一致。"""

    async def test_create_list_detail_carry_cover_variants(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        upload = (
            await client.post(
                "/api/v1/attachments/upload",
                files={"file": ("cover.png", make_png_bytes((1920, 1080)), "image/png")},
                headers=author_headers,
            )
        ).json()
        created = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(cover_image=upload["url"]),
                headers=author_headers,
            )
        ).json()
        assert [v["width"] for v in created["cover_variants"]] == [480, 800, 1600]

        listing = (await client.get("/api/v1/articles")).json()
        item = next(i for i in listing["items"] if i["id"] == created["id"])
        assert [v["width"] for v in item["cover_variants"]] == [480, 800, 1600]

        detail = (await client.get(f"/api/v1/articles/{created['slug']}")).json()
        assert [v["width"] for v in detail["cover_variants"]] == [480, 800, 1600]

    async def test_external_cover_falls_back_to_empty_variants(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        """外链封面查不到附件记录，静默落空列表而不是报错。"""
        created = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(cover_image="https://example.com/pic.jpg"),
                headers=author_headers,
            )
        ).json()
        assert created["cover_variants"] == []

    async def test_related_articles_carry_cover_variants(
        self, client: AsyncClient, author_headers: dict[str, str]
    ) -> None:
        upload = (
            await client.post(
                "/api/v1/attachments/upload",
                files={"file": ("rel.png", make_png_bytes((1920, 1080)), "image/png")},
                headers=author_headers,
            )
        ).json()
        first = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(tags=["共享标签"]),
                headers=author_headers,
            )
        ).json()
        second = (
            await client.post(
                "/api/v1/articles",
                json=make_article_payload(tags=["共享标签"], cover_image=upload["url"]),
                headers=author_headers,
            )
        ).json()

        related = (await client.get(f"/api/v1/articles/{first['id']}/related")).json()
        entry = next(i for i in related if i["id"] == second["id"])
        assert [v["width"] for v in entry["cover_variants"]] == [480, 800, 1600]
